FIELD_NAME_DOCUMENT = 'document'
FIELD_NAME_LABEL = 'label'

TOKEN_PAD = "[PAD]"
TOKEN_SOS = "[SOS]"
TOKEN_EOS = "[EOS]"
TOKEN_SEP = "[SEP]"
TOKEN_CLS = "[CLS]"

TOKEN_IDX_PAD = 0
TOKEN_IDX_SOS = 1
TOKEN_IDX_EOS = 2
TOKEN_IDX_SEP = 3
TOKEN_IDX_CLS = 4